version = 0.1

[default.global.parameters]
stack_name = "CommandHandlerApi"
region = "us-east-1"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = ["CAPABILITY_IAM", "CAPABILITY_NAMED_IAM"]
confirm_changeset = true
resolve_s3 = true

[default.deploy.parameters.parameter_overrides]
# replace with your key.
AppPublicKey = "201603e36d086b88ba355136c2296d44d3e58f4109f0c4baeead568cbf380d46"
[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true
# absolute path is recommended
template_file = "command_handler/template.yaml"
dependency_layer = false

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
