AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  # DiscordToken:
  #   Description: Discord Token. Must be prefixed with 'Bot' or 'Bearer'.
  #   NoEcho: true
  #   Type: String
  AppPublicKey:
    Description: Discord Application Public Key
    Type: String

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  CommandHandlerApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Name: CommandHandlerApi
      StageName: v1

  CommandHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Environment:
        Variables:
          APP_PUBLIC_KEY: !Ref AppPublicKey
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:017000801446:layer:AWSLambdaPowertoolsPythonV3-python313-x86_64:15
      Events:
        webhook:
          Type: HttpApi
          Properties:
            ApiId: !Ref CommandHandlerApi
            Path: /commands
            Method: post
# Outputs:
# ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
# Find out more about other implicit resources you can reference within SAM
# https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
# CommandHandlerApiEndpoint:
#   Description: API Gateway endpoint URL
#   Value: !Sub https://${CommandHandlerApi}.execute-api.${AWS::Region}.amazonaws.com/v1/start/
# CommandHandlerFunctionArn:
#   Description: Hello World Lambda Function ARN
#   Value: !GetAtt HelloWorldFunction.Arn
# HelloWorldFunctionIamRole:
#   Description: Implicit IAM Role created for Hello World function
#   Value: !GetAtt HelloWorldFunctionRole.Arn
