AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  LogLevel:
    Description: Log level for command_handler
    Type: String

  ServerInstanceId:
    Description: EC2 instance ID
    Type: String

  ServerRegionName:
    Description: EC2 region name
    Type: String

  AppPublicKey:
    Description: Discord Application Public Key
    Type: String

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  CommandHandlerApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Name: CommandHandlerApi
      StageName: v1

  CommandHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 1024
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Environment:
        Variables:
          APP_PUBLIC_KEY: !Ref AppPublicKey
          LOG_LEVEL: !Ref LogLevel
          SERVER_INSTANCE_ID: !Ref ServerInstanceId
          SERVER_REGION_NAME: !Ref ServerRegionName
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - ec2:DescribeInstances
              Resource: "*"
            - Effect: Allow
              Action:
                - ec2:StartInstances
                - ec2:StopInstances
              Resource: !Sub arn:aws:ec2:${ServerRegionName}:${AWS::AccountId}:instance/${ServerInstanceId}

      Events:
        webhook:
          Type: HttpApi
          Properties:
            ApiId: !Ref CommandHandlerApi
            Path: /commands
            Method: post
# Outputs:
# ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
# Find out more about other implicit resources you can reference within SAM
# https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
# CommandHandlerApiEndpoint:
#   Description: API Gateway endpoint URL
#   Value: !Sub https://${CommandHandlerApi}.execute-api.${AWS::Region}.amazonaws.com/v1/start/
# CommandHandlerFunctionArn:
#   Description: Hello World Lambda Function ARN
#   Value: !GetAtt HelloWorldFunction.Arn
# HelloWorldFunctionIamRole:
#   Description: Implicit IAM Role created for Hello World function
#   Value: !GetAtt HelloWorldFunctionRole.Arn
