AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: |
  command_handler

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  CommandHandlerApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Name: CommandHandlerApi
      StageName: v1

  CommandHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:017000801446:layer:AWSLambdaPowertoolsPythonV3-python313-x86_64:15
      Events:
        Start:
          Type: HttpApi
          Properties:
            ApiId: !Ref CommandHandlerApi
            Path: /start
            Method: post
        Stop:
          Type: HttpApi
          Properties:
            ApiId: !Ref CommandHandlerApi
            Path: /stop
            Method: post
# Outputs:
# ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
# Find out more about other implicit resources you can reference within SAM
# https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
# CommandHandlerApiEndpoint:
#   Description: API Gateway endpoint URL
#   Value: !Sub https://${CommandHandlerApi}.execute-api.${AWS::Region}.amazonaws.com/v1/start/
# CommandHandlerFunctionArn:
#   Description: Hello World Lambda Function ARN
#   Value: !GetAtt HelloWorldFunction.Arn
# HelloWorldFunctionIamRole:
#   Description: Implicit IAM Role created for Hello World function
#   Value: !GetAtt HelloWorldFunctionRole.Arn
